# Generated by Django 4.2.4 on 2023-08-13 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('event_description', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_recurring', models.BooleanField()),
                ('created_date', models.DateField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.event')),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MembersToLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.lobby')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.member')),
            ],
        ),
        migrations.AddField(
            model_name='lobby',
            name='manager',
            field=models.ForeignKey(db_column='manager', on_delete=django.db.models.deletion.CASCADE, to='scheduling.member'),
        ),
        migrations.CreateModel(
            name='EventInstanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rescheduled', models.BooleanField()),
                ('is_cancelled', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_date', models.DateField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.event')),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.manager')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.member')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='scheduling.event')),
                ('separation_count', models.SmallIntegerField(blank=True, null=True)),
                ('day_of_week', models.SmallIntegerField(blank=True, null=True)),
                ('week_of_month', models.SmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.SmallIntegerField(blank=True, null=True)),
                ('month_of_year', models.SmallIntegerField(blank=True, null=True)),
                ('recurring_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scheduling.recurringtype')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.lobby')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.member')),
            ],
            options={
                'unique_together': {('lobby', 'member')},
            },
        ),
        migrations.CreateModel(
            name='AttendEventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pending', models.BooleanField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_cancelled', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.member')),
            ],
            options={
                'unique_together': {('event', 'member')},
            },
        ),
    ]
