# Generated by Django 4.2.4 on 2023-10-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
